project:
  name: quickstart-sios-protection-suite
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  s3_bucket: ''
tests:
  sios-protection-suite-payg:
    parameters:
      AvailabilityZones: $[alfred_getaz_2]
      BastionAMIOS: Amazon-Linux2-HVM
      BastionInstanceType: t2.micro
      HomeDeleteOnTermination: 'true'
      HomeIops: '1000'
      HomeSize: '100'
      HomeVolumeType: General Purpose (SSD)
      KeyPairName: $[alfred_getkeypair]
      MirrorDeleteOnTermination: 'true'
      MirrorIops: '1000'
      MirrorSize: '100'
      MirrorVolumeType: General Purpose (SSD)
      NewRootPassword: $[alfred_genpass_14]
      Node1PrivateIP: 10.0.0.100
      Node2PrivateIP: 10.0.32.100
      PrivateSubnet1CIDR: 10.0.0.0/19
      PrivateSubnet2CIDR: 10.0.32.0/19
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      QSS3KeyPrefix: quickstart-sios-protection-suite/
      RemoteAccessCIDR: 0.0.0.0/0
      SIOSAMIType: PAYG
      SIOSLicenseKeyFtpURL: override
      SPSLInstanceNamePrefix: SPSL
      SPSLInstanceType: t2.medium
      VPCCIDR: 10.0.0.0/16
      WindowsJumpboxInstanceType: None
    regions:
    - us-east-1
    - ap-south-1
    - ca-central-1
    - eu-central-1
    s3_bucket: ''
    template: templates/sios-protection-suite-main.template.yaml
